# Generated by Django 6.0.3 on 2026-04-02 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('application', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tech_product_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_version', models.CharField(default='v1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='GSM (g/m²)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Width (cm)')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Thickness (mm)')),
                ('tensile_strength_warp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tensile Strength Warp (N)')),
                ('tensile_strength_weft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tensile Strength Weft (N)')),
                ('elongation_warp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Elongation Warp (%)')),
                ('elongation_weft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Elongation Weft (%)')),
                ('tear_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tear Strength (N)')),
                ('burst_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Burst Strength (kPa)')),
                ('air_permeability', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Air Permeability (mm/s)')),
                ('water_permeability', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Water Permeability')),
                ('uv_resistance', models.CharField(blank=True, max_length=100)),
                ('fire_resistance', models.CharField(blank=True, max_length=100)),
                ('composition', models.CharField(blank=True, max_length=200)),
                ('standard_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_specs', to='master_data.item')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_textile.technicalproductcategory')),
            ],
            options={
                'db_table': 'tech_performance_spec',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('sent', 'Sent to Customer'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='prepared', max_length=20)),
                ('customer_remarks', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
            ],
            options={
                'db_table': 'tech_sample',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('revision_number', models.CharField(default='R0', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('prepared_by', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_textile.performancespec')),
            ],
            options={
                'db_table': 'tech_data_sheet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RDProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('target_product', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('testing', 'Testing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('lead_engineer', models.CharField(blank=True, max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_textile.technicalproductcategory')),
            ],
            options={
                'db_table': 'tech_rd_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestingLabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(max_length=50, unique=True)),
                ('test_type', models.CharField(choices=[('physical', 'Physical Test'), ('chemical', 'Chemical Test'), ('mechanical', 'Mechanical Test'), ('flammability', 'Flammability Test'), ('biological', 'Biological Test'), ('other', 'Other')], default='physical', max_length=20)),
                ('test_date', models.DateField()),
                ('tested_by', models.CharField(max_length=100)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('gsm_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tensile_warp_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tensile_weft_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('elongation_warp_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('elongation_weft_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tear_strength_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('air_permeability_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('overall_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('standard_used', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
            ],
            options={
                'db_table': 'tech_testing_lab',
                'ordering': ['-test_date'],
            },
        ),
    ]
