# Generated by Django 6.0.3 on 2026-04-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('technical_textile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancespec',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='rdproject',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='sample',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='technicaldatasheet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='technicalproductcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='testinglabrecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
    ]
