# Generated by Django 6.0.3 on 2026-04-02 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('record_ref', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'med_audit_trail',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_lot', models.CharField(blank=True, max_length=200)),
                ('supplier_batch_ref', models.CharField(blank=True, max_length=200)),
                ('raw_material_coa', models.CharField(blank=True, max_length=200)),
                ('production_date', models.DateField()),
                ('production_line', models.CharField(blank=True, max_length=100)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('supervisor_name', models.CharField(blank=True, max_length=100)),
                ('qc_passed', models.BooleanField(default=False)),
                ('qc_checked_by', models.CharField(blank=True, max_length=100)),
                ('qc_date', models.DateField(blank=True, null=True)),
                ('qc_remarks', models.TextField(blank=True)),
                ('dispatched_to', models.CharField(blank=True, max_length=200)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traceability', to='production.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
            ],
            options={
                'db_table': 'med_batch_traceability',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_number', models.CharField(max_length=50, unique=True)),
                ('capa_type', models.CharField(choices=[('corrective', 'Corrective Action'), ('preventive', 'Preventive Action')], max_length=20)),
                ('source', models.CharField(choices=[('customer_complaint', 'Customer Complaint'), ('internal_audit', 'Internal Audit'), ('external_audit', 'External Audit'), ('product_failure', 'Product Failure'), ('supplier_issue', 'Supplier Issue'), ('process_deviation', 'Process Deviation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('effectiveness_check', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_created', to=settings.AUTH_USER_MODEL)),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.batch')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.item')),
            ],
            options={
                'db_table': 'med_capa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('iso_13485', 'ISO 13485'), ('iso_9001', 'ISO 9001'), ('fda_510k', 'FDA 510(k)'), ('ce_mark', 'CE Mark'), ('bis', 'BIS'), ('nabl', 'NABL'), ('who_gmp', 'WHO-GMP'), ('other', 'Other')], max_length=30)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issuing_body', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active / Valid'), ('expired', 'Expired'), ('pending', 'Pending Renewal'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='master_data.item')),
            ],
            options={
                'db_table': 'med_regulatory_compliance',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ShelfLifeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('shelf_life_months', models.IntegerField()),
                ('storage_condition', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('near_expiry', 'Near Expiry'), ('expired', 'Expired'), ('recalled', 'Recalled')], default='valid', max_length=20)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_life', to='production.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
            ],
            options={
                'db_table': 'med_shelf_life',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='SterilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterilization_method', models.CharField(choices=[('eo_gas', 'EO Gas'), ('gamma', 'Gamma Radiation'), ('steam', 'Steam Autoclave'), ('dry_heat', 'Dry Heat'), ('e_beam', 'E-Beam'), ('other', 'Other')], max_length=20)),
                ('sterilization_date', models.DateField()),
                ('sterilized_by', models.CharField(blank=True, max_length=200)),
                ('cycle_number', models.CharField(blank=True, max_length=50)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('exposure_time_min', models.IntegerField(blank=True, null=True)),
                ('test_result', models.CharField(choices=[('pass', 'Pass — Sterile'), ('fail', 'Fail — Not Sterile'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('tested_by', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sterility_records', to='production.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'med_sterility_record',
                'ordering': ['-sterilization_date'],
            },
        ),
    ]
