# Generated by Django 6.0.3 on 2026-05-15 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0003_customer_country_customer_currency_and_more'),
        ('product_development', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_po_ref', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateField()),
                ('ship_by_date', models.DateField(blank=True, null=True)),
                ('ex_factory_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('inspected', 'Inspected'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='masters.customer')),
                ('pd_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='product_development.pdrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_ref', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_management.customerorder')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('order_date', models.DateField()),
                ('ex_factory_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Factory'), ('confirmed', 'Factory Confirmed'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('qc_passed', 'QC Passed'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_orders', to='order_management.customerorder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_orders', to='masters.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_ref', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('co_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_management.customerorderitem')),
                ('factory_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_management.factoryorder')),
            ],
        ),
        migrations.CreateModel(
            name='TAMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=200)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('responsible', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_milestones', to='order_management.customerorder')),
                ('factory_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_milestones', to='order_management.factoryorder')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
    ]
