# Generated by Django 6.0.3 on 2026-05-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0003_customer_country_customer_currency_and_more'),
        ('order_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('inquiry_date', models.DateField()),
                ('required_delivery', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('target_fob_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('costing_done', 'Costing Done'), ('rfq_sent', 'RFQ Sent'), ('quoted', 'Quoted to Buyer'), ('confirmed', 'Converted to Order'), ('dropped', 'Dropped')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='masters.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='masters.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='masters.customer')),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inquiry', to='order_management.customerorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('trims_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cm_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('washing_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('testing_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('freight_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('overhead_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='order_management.buyerinquiry')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_ref', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size_range', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_management.buyerinquiry')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_date', models.DateField()),
                ('response_date', models.DateField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('unit_quoted', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_quoted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('sent', 'RFQ Sent'), ('received', 'Quote Received'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='sent', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='order_management.buyerinquiry')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='masters.vendor')),
            ],
            options={
                'ordering': ['unit_quoted'],
            },
        ),
    ]
