# Generated by Django 6.0.3 on 2026-05-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0003_customer_country_customer_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('request_date', models.DateField()),
                ('required_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('vendor_assigned', 'Vendor Assigned'), ('sample_in_progress', 'Sample In Progress'), ('sample_received', 'Sample Received'), ('testing', 'Testing In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pd_requests', to='masters.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDTechnicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction', models.CharField(blank=True, max_length=200)),
                ('size_dimension_variants', models.TextField(blank=True)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='pd/design_files/')),
                ('packaging_specs', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.fabrictype')),
                ('pd_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_spec', to='product_development.pdrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PDSpecTestingParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_override', models.CharField(blank=True, max_length=300)),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.testingparameter')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_params', to='product_development.pdtechnicalspec')),
            ],
        ),
        migrations.CreateModel(
            name='PDVendorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('sample_dev_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('ta_notes', models.TextField(blank=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('pd_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='product_development.pdrequest')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.vendor')),
            ],
            options={
                'unique_together': {('pd_request', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='PDSampleShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField()),
                ('lr_number', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pd_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_shipments', to='product_development.pdrequest')),
                ('vendor_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_development.pdvendorassignment')),
            ],
        ),
        migrations.CreateModel(
            name='PDSampleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='pd/invoices/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pd_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_invoices', to='product_development.pdrequest')),
                ('vendor_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_development.pdvendorassignment')),
            ],
        ),
    ]
