# Generated by Django 6.0.3 on 2026-04-18 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchentry',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.salesorder'),
        ),
    ]
