# Generated by Django 6.0.3 on 2026-04-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0003_initial'),
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0001_initial'),
        ('production_exec', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_exec.batch'),
        ),
        migrations.AddField(
            model_name='dispatchline',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dispatch.dispatchentry'),
        ),
        migrations.AddField(
            model_name='packinglabel',
            name='dispatch_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='dispatch.dispatchline'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dispatch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='dispatch.dispatchentry'),
        ),
    ]
