# Generated by Django 6.0.3 on 2026-04-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('production_exec', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(max_length=50, unique=True)),
                ('inspection_stage', models.CharField(choices=[('greige', 'Greige Inspection'), ('bare', 'Bare Inspection (Post Processing)'), ('finished', 'Final / Finished Inspection')], max_length=20)),
                ('inspection_date', models.DateField()),
                ('inspected_by', models.CharField(blank=True, max_length=100)),
                ('inspected_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('passed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('rejected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('rework_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail / Reject'), ('rework', 'Rework'), ('hold', 'Hold')], max_length=10)),
                ('defect_category', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='production_exec.batch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('defect_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.defecttype')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.inspection')),
            ],
        ),
    ]
