# Generated by Django 6.0.3 on 2026-04-19 04:54

import django.db.models.deletion
import quality.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('production_exec', '0003_yarnissue'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(default=quality.models.sample_test_number, max_length=50, unique=True)),
                ('test_date', models.DateField()),
                ('tested_by', models.CharField(blank=True, max_length=100)),
                ('tensile_strength', models.DecimalField(blank=True, decimal_places=2, help_text='N', max_digits=8, null=True)),
                ('elongation_pct', models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=7, null=True)),
                ('weight_per_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='gsm', max_digits=8, null=True)),
                ('breaking_strength', models.DecimalField(blank=True, decimal_places=2, help_text='N', max_digits=8, null=True)),
                ('tear_strength', models.DecimalField(blank=True, decimal_places=2, help_text='N', max_digits=8, null=True)),
                ('custom_param_name', models.CharField(blank=True, max_length=100)),
                ('custom_param_value', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional_pass', 'Conditional Pass'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_tests', to='production_exec.batch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date', '-created_at'],
            },
        ),
    ]
