# Generated by Django 6.0.3 on 2026-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_sampletest'),
    ]

    operations = [
        migrations.AddField(
            model_name='defecttype',
            name='defect_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='defecttype',
            name='severity',
            field=models.CharField(blank=True, default='minor', max_length=20),
        ),
    ]
