# Generated by Django 6.0.3 on 2026-04-19 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0002_productdesign_process_route'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('month_1_label', models.CharField(blank=True, max_length=20)),
                ('month_2_label', models.CharField(blank=True, max_length=20)),
                ('month_3_label', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='masters.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_1_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_2_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_3_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(default='kg', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.customerforecast')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.productdesign')),
            ],
            options={
                'ordering': ['product__design_code'],
            },
        ),
    ]
