# Generated by Django 6.0.3 on 2026-04-18 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0004_initial'),
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('production_exec', '0002_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, max_length=50)),
                ('material_name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(db_index=True, max_length=50)),
                ('process_stage', models.CharField(max_length=100)),
                ('machine_used', models.CharField(max_length=100)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('dispatch_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_records', to='production_exec.batch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.dispatchentry')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_records', to='purchase.lot')),
                ('process_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_exec.processentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
