# Generated by Django 6.0.3 on 2026-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceescalation',
            name='level1_grace_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours before escalating to L2'),
        ),
        migrations.AlterField(
            model_name='maintenanceescalation',
            name='level2_grace_hours',
            field=models.PositiveIntegerField(default=48, help_text='Hours before escalating to L3'),
        ),
        migrations.AlterField(
            model_name='maintenanceescalation',
            name='reminder_days',
            field=models.PositiveIntegerField(default=1, help_text='Days before due to send reminder'),
        ),
    ]
