# Generated by Django 6.0.3 on 2026-04-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenanceescalation_level1_grace_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='task_image',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/tasks/'),
        ),
    ]
