# Generated by Django 6.0.3 on 2026-05-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0004_initial'),
        ('finance', '0003_contraentry_creditnote_debitnote_fiscalyear_budget_and_more'),
        ('hr_payroll', '0003_professionaltaxslab_employeestatutory_leavetype_and_more'),
        ('master_data', '0006_alter_documentseries_document_type_companygroup_and_more'),
        ('masters', '0002_productdesign_process_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('goods_description', models.CharField(max_length=200)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_no_pan', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tcs_section',
                'ordering': ['section_code'],
            },
        ),
        migrations.CreateModel(
            name='TDSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('nature_of_payment', models.CharField(max_length=200)),
                ('rate_individual_huf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_company', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_no_pan', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('single_payment_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('surcharge_applicable', models.BooleanField(default=False)),
                ('health_cess_applicable', models.BooleanField(default=True)),
                ('is_salary_section', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tds_section',
                'ordering': ['section_code'],
            },
        ),
        migrations.CreateModel(
            name='TCSCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('customer_pan', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tcs_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('tcs_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=50)),
                ('bsr_code', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('collected', 'Collected — Pending Deposit'), ('deposited', 'Deposited to Govt')], default='collected', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.accountingperiod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcs_collections', to='masters.customer')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.fiscalyear')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcs_collections', to='finance.receipt')),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcs_collections', to='dispatch.salesinvoice')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tds_tcs.tcssection')),
            ],
            options={
                'db_table': 'tcs_collection',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorTDSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductee_type', models.CharField(choices=[('individual', 'Individual / HUF'), ('company', 'Company / Firm'), ('other', 'Other')], default='company', max_length=15)),
                ('tds_exempt', models.BooleanField(default=False)),
                ('lower_deduction_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_deduction_cert', models.CharField(blank=True, max_length=50)),
                ('cert_valid_from', models.DateField(blank=True, null=True)),
                ('cert_valid_to', models.DateField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tds_tcs.tdssection')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tds_config', to='masters.vendor')),
            ],
            options={
                'db_table': 'tds_vendor_config',
            },
        ),
        migrations.CreateModel(
            name='TDSReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('24Q', 'Form 24Q — Salary TDS'), ('26Q', 'Form 26Q — Non-salary TDS (Resident)'), ('27Q', 'Form 27Q — Non-salary TDS (Non-resident)'), ('27EQ', 'Form 27EQ — TCS Return')], max_length=5)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 — Apr to Jun'), ('Q2', 'Q2 — Jul to Sep'), ('Q3', 'Q3 — Oct to Dec'), ('Q4', 'Q4 — Jan to Mar')], max_length=2)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tds_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('revised', 'Revised')], default='draft', max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('ack_number', models.CharField(blank=True, max_length=50)),
                ('integration_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.fiscalyear')),
            ],
            options={
                'db_table': 'tds_return',
                'unique_together': {('company', 'fiscal_year', 'form_type', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='TDSDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_date', models.DateField()),
                ('party_type', models.CharField(choices=[('vendor', 'Vendor'), ('employee', 'Employee'), ('other', 'Other')], max_length=10)),
                ('party_pan', models.CharField(blank=True, max_length=20)),
                ('party_name', models.CharField(max_length=200)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tds_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tds', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=50)),
                ('bsr_code', models.CharField(blank=True, max_length=15)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('deducted', 'Deducted — Pending Deposit'), ('deposited', 'Deposited to Govt')], default='deducted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.accountingperiod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_deductions', to='hr_payroll.employee')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.fiscalyear')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_deductions', to='finance.payment')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_deductions', to='hr_payroll.payslip')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_deductions', to='masters.vendor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tds_tcs.tdssection')),
            ],
            options={
                'db_table': 'tds_deduction',
                'ordering': ['-deduction_date'],
                'indexes': [models.Index(fields=['company', 'fiscal_year', 'status'], name='tds_deducti_company_2f023d_idx')],
            },
        ),
    ]
