# Generated by Django 6.0.3 on 2026-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesign',
            name='process_route',
            field=models.CharField(choices=[('direct', 'Direct Sale (Buy → Sell)'), ('fabric_in', 'Fabric-In (Buy Fabric → Process → Sell)'), ('full_cycle', 'Full Cycle (Yarn → Weave → Process → Sell)')], default='full_cycle', max_length=20),
        ),
    ]
