# Generated by Django 6.0.3 on 2026-05-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0002_productdesign_process_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('CAD', 'CAD — Canadian Dollar'), ('INR', 'INR — Indian Rupee'), ('JPY', 'JPY — Japanese Yen'), ('OTHER', 'Other')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('brand', 'Brand'), ('retailer', 'Retailer'), ('agent', 'Buying Agent'), ('importer', 'Importer'), ('distributor', 'Distributor'), ('other', 'Other')], default='brand', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR — Indian Rupee'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('CNY', 'CNY — Chinese Yuan'), ('BDT', 'BDT — Bangladeshi Taka'), ('OTHER', 'Other')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('fabric', 'Fabric Supplier'), ('trim', 'Trim / Accessory Supplier'), ('testing_lab', 'Testing Lab'), ('logistics', 'Logistics / Freight'), ('buying_agent', 'Buying Agent'), ('other', 'Other')], default='manufacturer', max_length=20),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='masters.customer')),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='masters.category')),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_code', models.CharField(max_length=50, unique=True)),
                ('fabric_name', models.CharField(max_length=200)),
                ('construction', models.CharField(blank=True, max_length=200)),
                ('fiber_content', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
            ],
            options={
                'ordering': ['fabric_name'],
            },
        ),
        migrations.CreateModel(
            name='TestingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=50, unique=True)),
                ('parameter_name', models.CharField(max_length=200)),
                ('test_standard', models.CharField(blank=True, max_length=100)),
                ('acceptance_criteria', models.CharField(blank=True, max_length=300)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
            ],
            options={
                'ordering': ['parameter_name'],
            },
        ),
    ]
