// ============================================================
// FILE: pages/purchasing/CreatePurchaseOrderPage.js
// PURPOSE: Form to create a new Purchase Order.
//          Select supplier, warehouse, add multiple items.
//          Each item has quantity and price.
// ============================================================

import React, { useState, useEffect } from 'react';
import {
    Box, Typography, Button, TextField, Paper, MenuItem,
    Select, InputLabel, FormControl, Table, TableBody,
    TableCell, TableContainer, TableHead, TableRow,
    IconButton, Alert, Divider
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import { ResizableTable } from '../../components/common/ResizableTable';
import { useNavigate } from 'react-router-dom';

// Empty line template
const EMPTY_LINE = { item_id: '', ordered_quantity: '', unit_price: '', notes: '' };

function CreatePurchaseOrderPage() {
    const navigate = useNavigate();

    // Form header fields
    const [poNumber, setPoNumber]       = useState('');
    const [supplierId, setSupplierId]   = useState('');
    const [warehouseId, setWarehouseId] = useState('');
    const [orderDate, setOrderDate]     = useState(new Date().toISOString().split('T')[0]);
    const [expectedDate, setExpectedDate] = useState('');
    const [notes, setNotes]             = useState('');

    // PO lines (items)
    const [lines, setLines]             = useState([{ ...EMPTY_LINE }]);

    // Dropdown data
    const [suppliers, setSuppliers]     = useState([]);
    const [warehouses, setWarehouses]   = useState([]);
    const [items, setItems]             = useState([]);

    const [message, setMessage]         = useState('');
    const [messageType, setMessageType] = useState('success');

    useEffect(() => {
        fetchSuppliers();
        fetchWarehouses();
        fetchItems();
        // PO number auto-generated by backend
    }, []);

    // PO number is now auto-generated by backend (Format Panel settings)

    const fetchSuppliers = async () => {
        const res = await fetch('/api/master-data/suppliers/', { credentials: 'include' });
        const data = await res.json();
        setSuppliers(data.suppliers || []);
    };

    const fetchWarehouses = async () => {
        const res = await fetch('/api/master-data/warehouses/', { credentials: 'include' });
        const data = await res.json();
        setWarehouses(data.warehouses || []);
    };

    const fetchItems = async () => {
        const res = await fetch('/api/master-data/items/', { credentials: 'include' });
        const data = await res.json();
        setItems(data.items || []);
    };

    // Add a new empty line
    const addLine = () => setLines(prev => [...prev, { ...EMPTY_LINE }]);

    // Remove a line
    const removeLine = (index) => setLines(prev => prev.filter((_, i) => i !== index));

    // Update a line field
    const updateLine = (index, field, value) => {
        setLines(prev => prev.map((line, i) => i === index ? { ...line, [field]: value } : line));
    };

    // Calculate total
    const totalAmount = lines.reduce((sum, line) => {
        return sum + (parseFloat(line.ordered_quantity || 0) * parseFloat(line.unit_price || 0));
    }, 0);

    const handleSave = async () => {
        if (!supplierId || !warehouseId || !orderDate) {
            setMessage('Please fill in Supplier, Warehouse and Order Date.');
            setMessageType('error');
            return;
        }
        if (lines.some(l => !l.item_id || !l.ordered_quantity)) {
            setMessage('Please fill in Item and Quantity for all lines.');
            setMessageType('error');
            return;
        }

        const payload = {
            po_number:      poNumber,
            supplier_id:    supplierId,
            warehouse_id:   warehouseId,
            order_date:     orderDate,
            expected_date:  expectedDate || null,
            notes,
            lines: lines.map(l => ({
                item_id:            l.item_id,
                ordered_quantity:   l.ordered_quantity,
                unit_price:         l.unit_price || 0,
                notes:              l.notes,
            })),
        };

        const res = await fetch('/api/purchasing/purchase-orders/', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            credentials: 'include',
            body: JSON.stringify(payload),
        });
        const data = await res.json();
        if (res.ok) {
            setMessage('Purchase order created successfully!');
            setMessageType('success');
            setTimeout(() => navigate('/purchasing/purchase-orders'), 1500);
        } else {
            setMessage(data.message || 'Error creating purchase order.');
            setMessageType('error');
        }
    };

    return (
        <Box>
            <Typography variant="h5" fontWeight="bold" color="primary" mb={1}>
                Create Purchase Order
            </Typography>
            <Typography variant="body2" color="text.secondary" mb={3}>
                Create a new purchase order to buy from supplier
            </Typography>

            {message && <Alert severity={messageType} sx={{ mb: 2 }} onClose={() => setMessage('')}>{message}</Alert>}

            <Paper sx={{ p: 3, borderRadius: 2, boxShadow: 2 }}>

                {/* Header Section */}
                <Typography variant="subtitle1" fontWeight="bold" color="primary" mb={2}>
                    Order Details
                </Typography>
                <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 2, mb: 3 }}>
                    <TextField
                        label="PO Number"
                        value="Auto-generated"
                        disabled
                        helperText="Auto-assigned on save (Format Panel)"
                        sx={{ '& .MuiInputBase-input.Mui-disabled': {
                            WebkitTextFillColor: '#888', fontStyle: 'italic',
                        }}}
                    />

                    <FormControl>
                        <InputLabel>Supplier *</InputLabel>
                        <Select value={supplierId} label="Supplier *"
                            onChange={(e) => setSupplierId(e.target.value)}>
                            {suppliers.map(s => (
                                <MenuItem key={s.id} value={s.id}>{s.supplier_name}</MenuItem>
                            ))}
                        </Select>
                    </FormControl>

                    <FormControl>
                        <InputLabel>Warehouse *</InputLabel>
                        <Select value={warehouseId} label="Warehouse *"
                            onChange={(e) => setWarehouseId(e.target.value)}>
                            {warehouses.map(w => (
                                <MenuItem key={w.id} value={w.id}>{w.name}</MenuItem>
                            ))}
                        </Select>
                    </FormControl>

                    <TextField label="Order Date *" type="date" value={orderDate}
                        onChange={(e) => setOrderDate(e.target.value)}
                        InputLabelProps={{ shrink: true }} />

                    <TextField label="Expected Delivery Date" type="date" value={expectedDate}
                        onChange={(e) => setExpectedDate(e.target.value)}
                        InputLabelProps={{ shrink: true }} />

                    <TextField label="Notes" value={notes}
                        onChange={(e) => setNotes(e.target.value)} />
                </Box>

                <Divider sx={{ mb: 3 }} />

                {/* Items Section */}
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                    <Typography variant="subtitle1" fontWeight="bold" color="primary">
                        Items to Order
                    </Typography>
                    <Button startIcon={<AddIcon />} onClick={addLine} variant="outlined" size="small">
                        Add Item
                    </Button>
                </Box>

                <ResizableTable storageKey="createpurchaseorder">
                <TableContainer>
                    <Table size="small">
                        <TableHead sx={{ backgroundColor: 'action.hover' }}>
                            <TableRow>
                                <TableCell sx={{ fontWeight: 'bold' }}>#</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Item *</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Quantity *</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Unit Price (₹)</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Total (₹)</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Notes</TableCell>
                                <TableCell></TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {lines.map((line, index) => (
                                <TableRow key={index}>
                                    <TableCell>{index + 1}</TableCell>
                                    <TableCell sx={{ minWidth: 200 }}>
                                        <FormControl fullWidth size="small">
                                            <Select value={line.item_id}
                                                onChange={(e) => updateLine(index, 'item_id', e.target.value)}
                                                displayEmpty>
                                                <MenuItem value="">-- Select Item --</MenuItem>
                                                {items.map(i => (
                                                    <MenuItem key={i.id} value={i.id}>
                                                        {i.item_code} — {i.item_name}
                                                    </MenuItem>
                                                ))}
                                            </Select>
                                        </FormControl>
                                    </TableCell>
                                    <TableCell sx={{ width: 120 }}>
                                        <TextField size="small" type="number" value={line.ordered_quantity}
                                            onChange={(e) => updateLine(index, 'ordered_quantity', e.target.value)} />
                                    </TableCell>
                                    <TableCell sx={{ width: 120 }}>
                                        <TextField size="small" type="number" value={line.unit_price}
                                            onChange={(e) => updateLine(index, 'unit_price', e.target.value)} />
                                    </TableCell>
                                    <TableCell sx={{ width: 120 }}>
                                        <strong>
                                            {(parseFloat(line.ordered_quantity || 0) * parseFloat(line.unit_price || 0)).toFixed(2)}
                                        </strong>
                                    </TableCell>
                                    <TableCell>
                                        <TextField size="small" value={line.notes}
                                            onChange={(e) => updateLine(index, 'notes', e.target.value)} />
                                    </TableCell>
                                    <TableCell>
                                        <IconButton size="small" color="error" onClick={() => removeLine(index)}
                                            disabled={lines.length === 1}>
                                            <DeleteIcon fontSize="small" />
                                        </IconButton>
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </TableContainer>
            </ResizableTable>

                {/* Total */}
                <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 2, mb: 3 }}>
                    <Typography variant="h6" fontWeight="bold" color="primary">
                        Total Amount: ₹ {totalAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                    </Typography>
                </Box>

                <Divider sx={{ mb: 2 }} />

                {/* Buttons */}
                <Box sx={{ display: 'flex', justifyContent: 'flex-end', gap: 2 }}>
                    <Button variant="outlined" onClick={() => navigate('/purchasing/purchase-orders')}>
                        Cancel
                    </Button>
                    <Button variant="contained" onClick={handleSave} sx={{ backgroundColor: 'primary.main' }}>
                        Save Purchase Order
                    </Button>
                </Box>

            </Paper>
        </Box>
    );
}

export default CreatePurchaseOrderPage;
