# Generated by Django 6.0.3 on 2026-04-02 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=50, unique=True)),
                ('adjustment_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('physical_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment_line',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('production_in', 'Production In'), ('production_out', 'Production Out')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock',
                'ordering': ['item__item_code'],
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
