# Generated by Django 6.0.3 on 2026-04-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
    ]
