# Generated by Django 6.0.3 on 2026-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('item', 'Item Code'), ('warehouse', 'Warehouse Code'), ('supplier', 'Supplier Code'), ('customer', 'Customer Code'), ('employee', 'Employee Code'), ('purchase_order', 'Purchase Order'), ('grn', 'Goods Receipt Note'), ('inquiry', 'Sales Inquiry'), ('quotation', 'Quotation'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('work_order', 'Work Order'), ('batch', 'Production Batch'), ('stock_adjustment', 'Stock Adjustment'), ('capa', 'CAPA'), ('sample', 'Sample'), ('tds', 'Technical Data Sheet'), ('test_report', 'Test Report'), ('rd_project', 'R&D Project')], max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('include_fy', models.BooleanField(default=False)),
                ('separator', models.CharField(default='-', max_length=5)),
                ('padding', models.IntegerField(choices=[(2, '01  — 2 digits'), (3, '001 — 3 digits'), (4, '0001 — 4 digits'), (5, '00001 — 5 digits')], default=3)),
                ('starting_number', models.IntegerField(default=1)),
                ('current_number', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings_document_series',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settings_financial_year',
                'ordering': ['-start_date'],
            },
        ),
    ]
