# Generated by Django 6.0.3 on 2026-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_documentseries_financialyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', 'Quotation'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice')], max_length=30, unique=True)),
                ('email_subject', models.CharField(blank=True, default='', max_length=255)),
                ('email_body', models.TextField(blank=True, default='')),
                ('whatsapp_body', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings_message_template',
                'ordering': ['document_type'],
            },
        ),
    ]
