# Generated by Django 6.0.3 on 2026-05-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentseries',
            name='document_type',
            field=models.CharField(choices=[('item', 'Item Code'), ('warehouse', 'Warehouse Code'), ('supplier', 'Supplier Code'), ('customer', 'Customer Code'), ('employee', 'Employee Code'), ('purchase_order', 'Purchase Order'), ('grn', 'Goods Receipt Note'), ('inquiry', 'Sales Inquiry'), ('quotation', 'Quotation'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('work_order', 'Work Order'), ('batch', 'Production Batch'), ('stock_adjustment', 'Stock Adjustment'), ('capa', 'CAPA'), ('sample', 'Sample'), ('tds', 'Technical Data Sheet'), ('test_report', 'Test Report'), ('rd_project', 'R&D Project'), ('journal_entry', 'Journal Entry'), ('payment_voucher', 'Payment Voucher'), ('receipt_voucher', 'Receipt Voucher'), ('contra_voucher', 'Contra / Fund Transfer'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('cheque', 'Cheque'), ('bank_deposit', 'Bank Deposit'), ('payroll_run', 'Payroll Run'), ('payslip', 'Pay Slip')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='groups', to='master_data.company')),
            ],
            options={
                'db_table': 'master_company_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_start_month', models.IntegerField(choices=[(4, 'April 1  (India standard)'), (1, 'January 1 (Calendar year / USA)'), (7, 'July 1'), (10, 'October 1')], default=4)),
                ('fy_start_day', models.IntegerField(default=1)),
                ('tan_number', models.CharField(blank=True, max_length=20)),
                ('cin_number', models.CharField(blank=True, max_length=25)),
                ('msme_number', models.CharField(blank=True, max_length=50)),
                ('udyam_number', models.CharField(blank=True, max_length=30)),
                ('esic_code', models.CharField(blank=True, max_length=20)),
                ('pf_establishment', models.CharField(blank=True, max_length=30)),
                ('module_gst', models.BooleanField(default=True)),
                ('module_tds', models.BooleanField(default=True)),
                ('module_tcs', models.BooleanField(default=False)),
                ('module_payroll', models.BooleanField(default=True)),
                ('module_banking', models.BooleanField(default=True)),
                ('module_budget', models.BooleanField(default=False)),
                ('module_fixed_assets', models.BooleanField(default=False)),
                ('module_multi_currency', models.BooleanField(default=False)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('narration_on_journals', models.BooleanField(default=True)),
                ('round_off_limit', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='master_data.company')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'master_company_settings',
            },
        ),
    ]
