# Generated by Django 6.0.3 on 2026-04-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_number', models.CharField(max_length=50, unique=True)),
                ('received_date', models.DateField()),
                ('product_description', models.CharField(max_length=500)),
                ('end_use', models.CharField(choices=[('geotextile', 'Geotextile'), ('agrotextile', 'Agrotextile'), ('filtration', 'Filtration'), ('automotive', 'Automotive'), ('medical', 'Medical'), ('protective', 'Protective / FR'), ('industrial', 'Industrial'), ('other', 'Other')], default='other', max_length=50)),
                ('gsm_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tensile_requirement', models.CharField(blank=True, max_length=200)),
                ('coating_required', models.BooleanField(default=False)),
                ('coating_type', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_discussion', 'In Discussion'), ('sampling', 'Sampling'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.customer')),
            ],
            options={
                'db_table': 'sales_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('valid_until', models.DateField()),
                ('product_description', models.CharField(max_length=500)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lead_time_days', models.IntegerField(default=30)),
                ('spec_notes', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('delivery_terms', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.customer')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.customerinquiry')),
            ],
            options={
                'db_table': 'sales_quotation',
                'ordering': ['-created_at'],
            },
        ),
    ]
