# Generated by Django 6.0.3 on 2026-05-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_account_company_journalentry_company'),
        ('master_data', '0006_alter_documentseries_document_type_companygroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_start', models.CharField(max_length=15)),
                ('series_end', models.CharField(max_length=15)),
                ('leaves', models.IntegerField(default=50)),
                ('issued_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'banking_cheque_book',
            },
        ),
        migrations.CreateModel(
            name='ChequeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_type', models.CharField(choices=[('issued', 'Cheque Issued (Outgoing)'), ('received', 'Cheque Received (Incoming)')], max_length=10)),
                ('cheque_number', models.CharField(max_length=30)),
                ('cheque_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('party_name', models.CharField(max_length=200)),
                ('party_bank', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('deposited', 'Deposited'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled / Stopped'), ('stale', 'Stale / Expired')], default='issued', max_length=15)),
                ('deposited_date', models.DateField(blank=True, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('bounce_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banking_cheque_entry',
                'ordering': ['-cheque_date'],
            },
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_mode', models.CharField(choices=[('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI'), ('internal', 'Internal Transfer'), ('cheque', 'Cheque')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('narration', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banking_fund_transfer',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(default='Petty Cash', max_length=100)),
                ('custodian', models.CharField(blank=True, max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banking_petty_cash',
            },
        ),
        migrations.CreateModel(
            name='PettyCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('receipt', 'Cash Received (Replenishment)'), ('payment', 'Cash Paid (Expense)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=300)),
                ('voucher_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banking_petty_cash_entry',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('micr_code', models.CharField(blank=True, max_length=15)),
                ('swift_code', models.CharField(blank=True, max_length=15)),
                ('account_type', models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account'), ('od', 'Overdraft Account'), ('cc', 'Cash Credit Account'), ('fdrd', 'FD / RD')], default='current', max_length=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('bank_feed_enabled', models.BooleanField(default=False)),
                ('bank_feed_provider', models.CharField(blank=True, max_length=50)),
                ('bank_feed_account_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='finance.account')),
            ],
            options={
                'db_table': 'banking_bank_account',
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('statement_date', models.DateField()),
                ('statement_opening', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('statement_closing', models.DecimalField(decimal_places=2, max_digits=16)),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_cheques', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposits_in_transit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_charges_unrecorded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banking_reconciliation',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Money In)'), ('debit', 'Debit (Money Out)')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('narration', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('reconciled_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('payment', 'Payment Voucher'), ('receipt', 'Receipt Voucher'), ('transfer', 'Fund Transfer'), ('contra', 'Contra Entry'), ('import', 'Bank Statement Import'), ('bank_feed', 'Bank Feed (Auto-import)'), ('manual', 'Manual Entry')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
            ],
            options={
                'db_table': 'banking_transaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
