# Generated by Django 6.0.3 on 2026-05-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('finance', '0003_contraentry_creditnote_debitnote_fiscalyear_budget_and_more'),
        ('master_data', '0006_alter_documentseries_document_type_companygroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='finance.receipt'),
        ),
        migrations.AddField(
            model_name='chequebook',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_books', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='chequeentry',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='chequeentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='chequeentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='chequeentry',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='finance.receipt'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='fund_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='banking.fundtransfer'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.company'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account'),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account'),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='pettycashentry',
            name='petty_cash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='banking.pettycash'),
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliation',
            unique_together={('bank_account', 'statement_date')},
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'transaction_date'], name='banking_tra_bank_ac_388935_idx'),
        ),
    ]
