# Generated by Django 6.0.3 on 2026-04-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('quantity_produced', models.DecimalField(decimal_places=3, max_digits=12)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.item')),
            ],
            options={
                'db_table': 'production_batch',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_name', models.CharField(max_length=200)),
                ('quantity_produced', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_as_product', to='master_data.item')),
            ],
            options={
                'db_table': 'production_bom',
                'ordering': ['bom_name'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('waste_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.billofmaterials')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_as_material', to='master_data.item')),
            ],
            options={
                'db_table': 'production_bom_line',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.billofmaterials')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='master_data.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'production_work_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('checked_by', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('yarn_count_actual', models.CharField(blank=True, max_length=50)),
                ('strength_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('elongation_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unevenness_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.batch')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.workorder')),
            ],
            options={
                'db_table': 'production_quality_check',
                'ordering': ['-check_date'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.workorder'),
        ),
        migrations.CreateModel(
            name='WorkOrderMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.item')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.workorder')),
            ],
            options={
                'db_table': 'production_material_consumption',
            },
        ),
    ]
