# Generated by Django 6.0.3 on 2026-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_name', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('weaving', 'Weaving'), ('knitting', 'Knitting'), ('nonwoven', 'Nonwoven'), ('coating', 'Coating'), ('finishing', 'Finishing'), ('testing', 'Testing / Lab'), ('other', 'Other')], max_length=50)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_unit', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('breakdown', 'Breakdown')], default='active', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'production_machine',
                'ordering': ['machine_code'],
            },
        ),
    ]
