// ============================================================
// PAGE: GRN — Goods Receipt Note + Lot Creation Popup
// This is the MOST IMPORTANT frontend screen.
// When user confirms GRN → they split received qty into lots.
// Each lot gets: qty, color code, color name, location, vendor lot ref.
// LOT numbers auto-generated by backend.
// ============================================================
import { useState, useEffect, useCallback } from 'react';

export default function GRNPage() {
    const [grns,      setGrns]      = useState([]);
    const [pos,       setPOs]       = useState([]);
    const [locations, setLocations] = useState([]);
    const [filterPO,  setFilterPO]  = useState('');
    const [status,    setStatus]    = useState('');

    // GRN Create modal
    const [newGRN,    setNewGRN]    = useState(false);
    const [grnForm,   setGrnForm]   = useState({ purchase_order_id: '', receipt_date: today(), vendor_invoice_number: '', notes: '' });
    const [poLines,   setPoLines]   = useState([]);   // lines from selected PO
    const [grnLines,  setGrnLines]  = useState([]);   // user-entered received qtys

    // Lot creation popup
    const [lotModal,  setLotModal]  = useState(null); // grn object to confirm lots for
    const [lotSplits, setLotSplits] = useState([]);   // array of { grn_line_id, lots: [{qty, color_code, color_name, location_id, vendor_lot_ref}] }

    const [saving,    setSaving]    = useState(false);
    const [msg,       setMsg]       = useState('');

    function today() { return new Date().toISOString().split('T')[0]; }

    const load = useCallback(async () => {
        const p = new URLSearchParams();
        if (filterPO) p.set('po_id', filterPO);
        if (status)   p.set('status', status);
        const res = await fetch(`/api/purchase/grn/?${p}`, { credentials: 'include' });
        const d = await res.json(); setGrns(d.grns || []);
    }, [filterPO, status]);

    useEffect(() => { load(); }, [load]);
    useEffect(() => {
        fetch('/api/purchase/po/?status=confirmed', { credentials: 'include' }).then(r => r.json()).then(d => setPOs(d.purchase_orders || []));
        fetch('/api/masters/locations/?location_type=raw_material', { credentials: 'include' }).then(r => r.json()).then(d => setLocations(d.locations || []));
    }, []);

    // When PO selected in new GRN form — load its lines
    const onPOSelect = async (poId) => {
        setGrnForm(p => ({ ...p, purchase_order_id: poId }));
        if (!poId) { setPoLines([]); setGrnLines([]); return; }
        const res = await fetch(`/api/purchase/po/${poId}/`, { credentials: 'include' });
        const d = await res.json();
        const lines = d.purchase_order?.lines || [];
        setPoLines(lines);
        setGrnLines(lines.map(l => ({ po_line_id: l.id, received_quantity: '' })));
    };

    const saveGRN = async () => {
        if (!grnForm.purchase_order_id) { setMsg('Select a PO'); return; }
        setSaving(true);
        const body = { ...grnForm, lines: grnLines.filter(l => l.received_quantity > 0) };
        const res = await fetch('/api/purchase/grn/', {
            method: 'POST', credentials: 'include',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
        });
        setSaving(false);
        if (res.ok) {
            setNewGRN(false);
            setGrnForm({ purchase_order_id: '', receipt_date: today(), vendor_invoice_number: '', notes: '' });
            setPoLines([]); setGrnLines([]);
            load();
        } else { const d = await res.json(); setMsg(d.error || 'Error'); }
    };

    // Open lot creation popup for a draft GRN
    const openLotPopup = async (grn) => {
        // Fetch GRN with lines
        const res = await fetch(`/api/purchase/grn/${grn.id}/`, { credentials: 'include' });
        const d = await res.json();
        const grnData = d.grn;
        setLotModal(grnData);

        // Init lotSplits: one split per line, starting with one lot per line
        const splits = (grnData.lines || []).map(line => ({
            grn_line_id: line.id,
            material_name: line.material_name,
            received_qty: line.received_quantity,
            lots: [{
                quantity: line.received_quantity,
                color_code: '',
                color_name: '',
                location_id: locations[0]?.id || '',
                vendor_lot_ref: '',
            }],
        }));
        setLotSplits(splits);
        setMsg('');
    };

    const addLotSplit = (splitIdx) => {
        setLotSplits(p => p.map((s, i) => i === splitIdx
            ? { ...s, lots: [...s.lots, { quantity: '', color_code: '', color_name: '', location_id: locations[0]?.id || '', vendor_lot_ref: '' }] }
            : s
        ));
    };

    const removeLotSplit = (splitIdx, lotIdx) => {
        setLotSplits(p => p.map((s, i) => i === splitIdx
            ? { ...s, lots: s.lots.filter((_, j) => j !== lotIdx) }
            : s
        ));
    };

    const updateLot = (splitIdx, lotIdx, field, val) => {
        setLotSplits(p => p.map((s, i) => i === splitIdx
            ? { ...s, lots: s.lots.map((l, j) => j === lotIdx ? { ...l, [field]: val } : l) }
            : s
        ));
    };

    const confirmLots = async () => {
        setSaving(true);
        const body = {
            grn_id: lotModal.id,
            lot_splits: lotSplits.map(s => ({
                grn_line_id: s.grn_line_id,
                lots: s.lots.map(l => ({
                    quantity: parseFloat(l.quantity) || 0,
                    color_code: l.color_code,
                    color_name: l.color_name,
                    location_id: l.location_id || null,
                    vendor_lot_ref: l.vendor_lot_ref,
                })).filter(l => l.quantity > 0),
            })),
        };
        const res = await fetch('/api/purchase/grn/confirm-lots/', {
            method: 'POST', credentials: 'include',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
        });
        setSaving(false);
        if (res.ok) {
            const d = await res.json();
            setLotModal(null);
            load();
            alert(`✓ ${d.message}\n\nLots created:\n${d.lots.map(l => l.lot_number).join('\n')}`);
        } else {
            const d = await res.json();
            setMsg(d.error || 'Error creating lots');
        }
    };

    return (
        <div style={{ padding: 24 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                <h2 style={{ margin: 0, fontSize: 22, fontWeight: 700 }}>Goods Receipt Notes (GRN)</h2>
                <button onClick={() => { setMsg(''); setNewGRN(true); }} style={btn('#3b82f6')}>+ New GRN</button>
            </div>

            {/* Filters */}
            <div style={{ display: 'flex', gap: 12, marginBottom: 16 }}>
                <select value={filterPO} onChange={e => setFilterPO(e.target.value)} style={selectS}>
                    <option value="">All Purchase Orders</option>
                    {pos.map(p => <option key={p.id} value={p.id}>{p.po_number} — {p.vendor_name}</option>)}
                </select>
                <select value={status} onChange={e => setStatus(e.target.value)} style={selectS}>
                    <option value="">All Status</option>
                    <option value="draft">Draft</option>
                    <option value="confirmed">Confirmed</option>
                </select>
            </div>

            {/* GRN List */}
            <table style={tableS}><thead><tr style={{ background: '#1e293b', color: '#fff' }}>
                {['GRN Number', 'PO Number', 'Vendor', 'Receipt Date', 'Vendor Invoice', 'Status', 'Actions'].map(h =>
                    <th key={h} style={thS}>{h}</th>)}
            </tr></thead><tbody>
                {grns.map((r, i) => (
                    <tr key={r.id} style={{ background: i % 2 === 0 ? '#f8fafc' : '#fff' }}>
                        <td style={tdS}><b style={{ color: '#3b82f6' }}>{r.grn_number}</b></td>
                        <td style={tdS}>{r.po_number}</td>
                        <td style={tdS}>{r.vendor_name}</td>
                        <td style={tdS}>{r.receipt_date}</td>
                        <td style={tdS}>{r.vendor_invoice_number || '—'}</td>
                        <td style={tdS}>
                            <span style={{ display: 'inline-block', padding: '3px 10px', borderRadius: 12, fontSize: 11, fontWeight: 700,
                                background: r.status === 'confirmed' ? '#dcfce7' : '#fef3c7',
                                color: r.status === 'confirmed' ? '#166534' : '#92400e' }}>
                                {r.status}
                            </span>
                        </td>
                        <td style={tdS}>
                            {r.status === 'draft' && (
                                <button onClick={() => openLotPopup(r)} style={btn('#ec4899')}>
                                    Confirm + Create Lots
                                </button>
                            )}
                            {r.status === 'confirmed' && <span style={{ color: '#10b981', fontSize: 12 }}>✓ Lots Created</span>}
                        </td>
                    </tr>
                ))}
                {grns.length === 0 && <tr><td colSpan={7} style={{ textAlign: 'center', padding: 40, color: '#94a3b8' }}>No GRNs found</td></tr>}
            </tbody></table>

            {/* New GRN Modal */}
            {newGRN && (
                <div style={overlay}>
                    <div style={{ ...mBox, width: 720 }}>
                        <h3 style={{ margin: '0 0 20px' }}>New Goods Receipt Note</h3>
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 16 }}>
                            <F label="Purchase Order *">
                                <select style={inpS} value={grnForm.purchase_order_id} onChange={e => onPOSelect(e.target.value)}>
                                    <option value="">-- Select Confirmed PO --</option>
                                    {pos.map(p => <option key={p.id} value={p.id}>{p.po_number} — {p.vendor_name}</option>)}
                                </select>
                            </F>
                            <F label="Receipt Date"><input style={inpS} type="date" value={grnForm.receipt_date} onChange={e => setGrnForm(p => ({ ...p, receipt_date: e.target.value }))} /></F>
                            <F label="Vendor Invoice Number"><input style={inpS} value={grnForm.vendor_invoice_number} onChange={e => setGrnForm(p => ({ ...p, vendor_invoice_number: e.target.value }))} /></F>
                        </div>

                        {/* PO Lines — enter received qty */}
                        {poLines.length > 0 && (
                            <>
                                <b style={{ fontSize: 13 }}>Enter Received Quantities:</b>
                                <table style={{ ...tableS, marginTop: 10 }}><thead><tr style={{ background: '#334155', color: '#fff' }}>
                                    {['Material', 'Ordered Qty', 'Received Qty'].map(h => <th key={h} style={{ ...thS, padding: '8px 12px', fontSize: 11 }}>{h}</th>)}
                                </tr></thead><tbody>
                                    {poLines.map((pl, i) => (
                                        <tr key={i} style={{ background: i % 2 === 0 ? '#f8fafc' : '#fff' }}>
                                            <td style={{ ...tdS, padding: '8px 12px' }}>{pl.material_name} <span style={{ color: '#64748b', fontSize: 11 }}>({pl.uom_name})</span></td>
                                            <td style={{ ...tdS, padding: '8px 12px' }}>{pl.ordered_quantity}</td>
                                            <td style={{ ...tdS, padding: '8px 12px' }}>
                                                <input type="number" step="0.001"
                                                    style={{ ...inpS, width: 120 }}
                                                    placeholder="Qty received"
                                                    value={grnLines[i]?.received_quantity || ''}
                                                    onChange={e => setGrnLines(prev => prev.map((l, j) => j === i ? { ...l, received_quantity: e.target.value } : l))} />
                                            </td>
                                        </tr>
                                    ))}
                                </tbody></table>
                            </>
                        )}

                        <F label="Notes" style={{ marginTop: 14 }}>
                            <textarea style={{ ...inpS, height: 60, resize: 'vertical', marginTop: 4 }}
                                value={grnForm.notes} onChange={e => setGrnForm(p => ({ ...p, notes: e.target.value }))} />
                        </F>
                        {msg && <div style={{ color: '#ef4444', marginTop: 8 }}>{msg}</div>}
                        <div style={{ display: 'flex', gap: 10, marginTop: 20, justifyContent: 'flex-end' }}>
                            <button onClick={() => setNewGRN(false)} style={smallBtn('#64748b')}>Cancel</button>
                            <button onClick={saveGRN} disabled={saving} style={btn('#3b82f6')}>{saving ? 'Saving…' : 'Save GRN (Draft)'}</button>
                        </div>
                    </div>
                </div>
            )}

            {/* LOT CREATION POPUP — THE KEY SCREEN */}
            {lotModal && (
                <div style={overlay}>
                    <div style={{ ...mBox, width: 860 }}>
                        <div style={{ marginBottom: 20 }}>
                            <h3 style={{ margin: '0 0 4px' }}>Create Lots — {lotModal.grn_number}</h3>
                            <p style={{ margin: 0, color: '#64748b', fontSize: 13 }}>
                                Split each received material into individual LOTs. Each LOT gets a unique number for traceability.
                            </p>
                        </div>

                        {lotSplits.map((split, si) => (
                            <div key={si} style={{ border: '1px solid #e2e8f0', borderRadius: 10, padding: 16, marginBottom: 16, background: '#f8fafc' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                                    <div>
                                        <b style={{ fontSize: 14 }}>{split.material_name}</b>
                                        <span style={{ marginLeft: 10, color: '#64748b', fontSize: 12 }}>Received: {split.received_qty}</span>
                                        <span style={{ marginLeft: 10, color: '#10b981', fontSize: 12, fontWeight: 600 }}>
                                            Sum of lots: {split.lots.reduce((sum, l) => sum + (parseFloat(l.quantity) || 0), 0).toFixed(3)}
                                        </span>
                                    </div>
                                    <button onClick={() => addLotSplit(si)} style={smallBtn('#3b82f6')}>+ Add Lot</button>
                                </div>

                                {split.lots.map((lot, li) => (
                                    <div key={li} style={{ display: 'grid', gridTemplateColumns: '100px 100px 130px 1fr 130px 30px', gap: 8, marginBottom: 8, alignItems: 'end' }}>
                                        <F label={li === 0 ? 'Quantity *' : ''}>
                                            <input style={inpS} type="number" step="0.001" placeholder="Qty"
                                                value={lot.quantity}
                                                onChange={e => updateLot(si, li, 'quantity', e.target.value)} />
                                        </F>
                                        <F label={li === 0 ? 'Color Code' : ''}>
                                            <input style={inpS} placeholder="e.g. R01"
                                                value={lot.color_code}
                                                onChange={e => updateLot(si, li, 'color_code', e.target.value)} />
                                        </F>
                                        <F label={li === 0 ? 'Color Name' : ''}>
                                            <input style={inpS} placeholder="e.g. Red"
                                                value={lot.color_name}
                                                onChange={e => updateLot(si, li, 'color_name', e.target.value)} />
                                        </F>
                                        <F label={li === 0 ? 'Location' : ''}>
                                            <select style={inpS} value={lot.location_id}
                                                onChange={e => updateLot(si, li, 'location_id', e.target.value)}>
                                                <option value="">-- Location --</option>
                                                {locations.map(loc => <option key={loc.id} value={loc.id}>{loc.name}</option>)}
                                            </select>
                                        </F>
                                        <F label={li === 0 ? 'Vendor Lot Ref' : ''}>
                                            <input style={inpS} placeholder="Vendor's lot no"
                                                value={lot.vendor_lot_ref}
                                                onChange={e => updateLot(si, li, 'vendor_lot_ref', e.target.value)} />
                                        </F>
                                        <div style={{ paddingBottom: 2 }}>
                                            {split.lots.length > 1 && (
                                                <button onClick={() => removeLotSplit(si, li)}
                                                    style={{ background: 'none', border: 'none', color: '#ef4444', cursor: 'pointer', fontSize: 18, lineHeight: 1 }}>✕</button>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        ))}

                        {msg && <div style={{ color: '#ef4444', padding: '8px 0' }}>{msg}</div>}

                        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
                            <button onClick={() => setLotModal(null)} style={smallBtn('#64748b')}>Cancel</button>
                            <button onClick={confirmLots} disabled={saving} style={btn('#ec4899')}>
                                {saving ? 'Creating Lots…' : '✓ Confirm GRN & Create Lots'}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

const F = ({ label, children }) => (
    <div><label style={{ display: 'block', fontSize: 11, fontWeight: 600, color: '#475569', marginBottom: 3 }}>{label || '\u00A0'}</label>{children}</div>
);
const btn      = (bg) => ({ padding: '8px 18px', background: bg, color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontWeight: 600, fontSize: 13 });
const smallBtn = (bg) => ({ padding: '4px 10px', background: bg, color: '#fff', border: 'none', borderRadius: 5, cursor: 'pointer', fontSize: 12, marginRight: 4 });
const selectS  = { padding: '8px 12px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13 };
const tableS   = { width: '100%', borderCollapse: 'collapse', fontSize: 13 };
const thS      = { padding: '10px 14px', textAlign: 'left', fontWeight: 600, fontSize: 12 };
const tdS      = { padding: '10px 14px', borderBottom: '1px solid #f1f5f9', verticalAlign: 'middle' };
const overlay  = { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1300 };
const mBox     = { background: '#fff', borderRadius: 12, padding: 28, width: 680, maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' };
const inpS     = { width: '100%', padding: '7px 10px', borderRadius: 7, border: '1px solid #e2e8f0', fontSize: 12, boxSizing: 'border-box' };
