# Generated by Django 6.0.3 on 2026-04-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEntryLotInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('entry_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='morning', max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('output_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('rejection_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('daily_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.dailyplan')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.machine')),
                ('process_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.process')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_entries', to='planning.productionorder')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeamOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('issued_to_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.machine')),
                ('process_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_exec.processentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('qc_pending', 'QC Pending'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed / Rejected'), ('rework', 'Rework'), ('finished', 'Finished Goods'), ('dispatched', 'Dispatched')], default='in_process', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('process_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.process')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='planning.productionorder')),
                ('process_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production_exec.processentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
