# Generated by Django 6.0.3 on 2026-04-18 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_exec', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processentrylotinput',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.lot'),
        ),
        migrations.AddField(
            model_name='processentrylotinput',
            name='process_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_inputs', to='production_exec.processentry'),
        ),
    ]
