# Generated by Django 6.0.3 on 2026-04-19 04:54

import django.db.models.deletion
import production_exec.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('masters', '0001_initial'),
        ('planning', '0001_initial'),
        ('production_exec', '0002_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YarnIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(default=production_exec.models.yarn_issue_number, max_length=50, unique=True)),
                ('issued_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purpose', models.CharField(choices=[('warp', 'Warp Yarn Issue'), ('weft', 'Weft / Filling Issue'), ('other', 'Other Material Issue')], default='warp', max_length=20)),
                ('issue_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='morning', max_length=20)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issued_to_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_issues', to='masters.machine')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_issues', to='purchase.lot')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_issues', to='planning.productionorder')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
