# Generated by Django 6.0.3 on 2026-04-19 09:18

import django.db.models.deletion
import production_exec.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_initial'),
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('production_exec', '0003_yarnissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_number', models.CharField(default=production_exec.models.dc_number, max_length=50, unique=True)),
                ('dc_date', models.DateField()),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('lr_number', models.CharField(blank=True, max_length=100)),
                ('transporter', models.CharField(blank=True, max_length=200)),
                ('eway_bill', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('returned', 'Returned'), ('converted', 'Converted to Invoice')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan', to='dispatch.dispatchentry')),
            ],
            options={
                'ordering': ['-dc_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbossingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_code', models.CharField(blank=True, max_length=100)),
                ('pressure_bar', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('temp_celsius', models.IntegerField(default=0)),
                ('speed_mpm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('process_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embossing_detail', to='production_exec.processentry')),
            ],
        ),
        migrations.CreateModel(
            name='LaminationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_type', models.CharField(blank=True, max_length=100)),
                ('film_gsm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('coat_weight_gsm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('adhesive_type', models.CharField(blank=True, max_length=100)),
                ('line_speed_mpm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('curing_temp', models.IntegerField(default=0)),
                ('process_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lamination_detail', to='production_exec.processentry')),
            ],
        ),
        migrations.CreateModel(
            name='StenterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_zone1', models.IntegerField(default=0)),
                ('temp_zone2', models.IntegerField(default=0)),
                ('temp_zone3', models.IntegerField(default=0)),
                ('temp_zone4', models.IntegerField(default=0)),
                ('speed_mpm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overfeed_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('chemical_recipe', models.CharField(blank=True, max_length=200)),
                ('process_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stenter_detail', to='production_exec.processentry')),
            ],
        ),
        migrations.CreateModel(
            name='TumblerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_celsius', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('softener_name', models.CharField(blank=True, max_length=100)),
                ('softener_qty_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('anti_wrinkle', models.CharField(blank=True, max_length=100)),
                ('process_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tumbler_detail', to='production_exec.processentry')),
            ],
        ),
        migrations.CreateModel(
            name='WarpingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_count', models.IntegerField(default=1)),
                ('total_ends', models.IntegerField(default=0)),
                ('reed_count', models.CharField(blank=True, max_length=30)),
                ('warp_length_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sizing_done', models.BooleanField(default=False)),
                ('beam_numbers', models.TextField(blank=True)),
                ('warp_tension_g', models.IntegerField(default=0)),
                ('process_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warping_detail', to='production_exec.processentry')),
            ],
        ),
        migrations.CreateModel(
            name='WeavingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loom_rpm', models.IntegerField(default=0)),
                ('picks_per_cm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weft_pattern', models.CharField(blank=True, max_length=100)),
                ('fabric_width_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('efficiency_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('beam_outward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_exec.beamoutward')),
                ('process_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weaving_detail', to='production_exec.processentry')),
            ],
        ),
    ]
