# Generated by Django 6.0.3 on 2026-05-15 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0005_customer_company_item_company_supplier_company_and_more'),
        ('order_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('fob_price_per_pc', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_quantity', models.IntegerField(default=0)),
                ('fabric_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('trim_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('embroidery_print', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('washing_finishing', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cm_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('testing_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('inspection_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('freight_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing_sheet', to='order_management.customerorder')),
            ],
        ),
        migrations.CreateModel(
            name='PreShipmentInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psi_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('inspection_date', models.DateField()),
                ('inspector_name', models.CharField(blank=True, max_length=200)),
                ('inspection_agency', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('pass_remarks', 'Pass with Remarks'), ('fail', 'Fail'), ('re_inspect', 'Re-Inspection Required')], default='pending', max_length=20)),
                ('quantity_inspected', models.IntegerField(default=0)),
                ('quantity_passed', models.IntegerField(default=0)),
                ('aql_level', models.CharField(blank=True, default='2.5', max_length=20)),
                ('critical_defects', models.IntegerField(default=0)),
                ('major_defects', models.IntegerField(default=0)),
                ('minor_defects', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('report_file_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_list', to='master_data.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_list', to='order_management.customerorder')),
                ('factory_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psi_list', to='order_management.factoryorder')),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PSIChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], default='na', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('psi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='shipment.preshipmentinspection')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('mode', models.CharField(choices=[('sea', 'Sea Freight'), ('air', 'Air Freight'), ('land', 'Land/Road'), ('courier', 'Courier')], default='sea', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booking Confirmed'), ('loaded', 'Loaded / Stuffed'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Port'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('shipper', models.CharField(blank=True, max_length=200)),
                ('consignee', models.CharField(blank=True, max_length=200)),
                ('forwarder', models.CharField(blank=True, max_length=200)),
                ('port_of_loading', models.CharField(blank=True, max_length=100)),
                ('port_of_discharge', models.CharField(blank=True, max_length=100)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('actual_departure', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('bl_number', models.CharField(blank=True, max_length=100)),
                ('container_number', models.CharField(blank=True, max_length=100)),
                ('total_cartons', models.IntegerField(default=0)),
                ('total_qty', models.IntegerField(default=0)),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cbm', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='master_data.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='order_management.customerorder')),
                ('factory_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='order_management.factoryorder')),
                ('psi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipment.preshipmentinspection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
